name: Cypress Regression Tests

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cypress Run
        uses: cypress-io/github-action@v6
        with:
          command: npm run regression

      - name: Upload Screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Upload Videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos

      - name: Upload HTML Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-reports
          path: cypress/reports